/** Declaration file generated by dts-gen */

export = herrtxbias_cachet_api;

declare class herrtxbias_cachet_api {
    constructor(options: any);

    getComponentById(id: any): any;

    getComponentGroups(filter: any): any;

    getComponents(filter: any): any;

    getIncidents(filter: any): any;

    getVersion(): any;

    publishMetricPoint(metricPoint: any): any;

    reportIncident(incident: any): any;

    updateComponent(component: any): any;

    updateIncident(incident: any): any;

}

